# baseURL = 'http://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'
# theme = ["risotto"]

baseURL = "https://yossicohn.github.io/"
theme = "risotto"
title = "Yossi Cohn"
author = "Yossi Cohn"
copyright = "© 2022 Yossi Cohn"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "Yossi Cohn"
description = "[Reach out](https://yossicohn.github.io/)"
# logo = "images/rice.svg"


# Sidebar: social links
# Available icon sets:
# * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/yossicohn"


[[params.socialLinks]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/yossicohn/"

[[params.socialLinks]]
icon = "fab fa-medium"
title = "Medium"
url = "https://medium.com/@yossicohn"

[[params.socialLinks]]
icon = "fab fa-twitter"
title = "Twitter"
url = "http://twitter.com/yossiku"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

#    [[menu.main]]
#     identifier = "CV"
#     name = "CV"
#     url = "/cv/"
#     weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = false

staticDir = ['static']

# [languages]
#   [languages.en]
#     baseURL = 'https://example.com'
#     languageName = 'English'
#     staticDir = 'static'
#     title = 'In English'
#     weight = 2
[_build]
  list = 'always'
  publishResources = true
  render = 'always'